# Generated by Django 4.2.1 on 2023-05-30 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date_time', models.DateTimeField()),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='tournament.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='tournament.team')),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team_score', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('away_team_score', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('home_team_formation', models.CharField(max_length=10)),
                ('away_team_formation', models.CharField(max_length=10)),
                ('referee', models.CharField(max_length=30)),
                ('fixture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scores_fixtures.fixture')),
            ],
        ),
        migrations.CreateModel(
            name='GoalScorers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(default=0)),
                ('away_assist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_assist', to='tournament.team')),
                ('away_scorer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_scorer', to='tournament.team')),
                ('home_assist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_assist', to='tournament.team')),
                ('home_scorer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_scorer', to='tournament.team')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores_fixtures.match')),
            ],
            options={
                'verbose_name_plural': 'Goal Scorers',
            },
        ),
    ]
