# Generated by Django 4.2.1 on 2023-06-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores_fixtures', '0002_alter_fixture_tournament_alter_match_fixture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Matches'},
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('not_started', 'not_started'), ('ON', 'ON'), ('HF', 'HF'), ('FT', 'FT'), ('ET', 'ET'), ('postponed', 'postponed')], default='not_started', max_length=15),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team_formation',
            field=models.CharField(default='4-4-2', max_length=10),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team_formation',
            field=models.CharField(default='4-4-2', max_length=10),
        ),
    ]
