# Generated by Django 4.2.1 on 2023-06-03 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
        ('scores_fixtures', '0003_alter_match_options_match_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalscorers',
            name='away_assist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_assist', to='tournament.player'),
        ),
        migrations.AlterField(
            model_name='goalscorers',
            name='away_scorer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_scorer', to='tournament.player'),
        ),
        migrations.AlterField(
            model_name='goalscorers',
            name='home_assist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_assist', to='tournament.player'),
        ),
        migrations.AlterField(
            model_name='goalscorers',
            name='home_scorer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_scorer', to='tournament.player'),
        ),
    ]
