# Generated by Django 4.2.1 on 2023-06-03 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores_fixtures', '0004_alter_goalscorers_away_assist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='time',
            field=models.TimeField(default='00:00'),
        ),
    ]
