# Generated by Django 4.2.1 on 2023-06-04 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores_fixtures', '0005_match_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goalscorers',
            old_name='home_assist',
            new_name='assist',
        ),
        migrations.RenameField(
            model_name='goalscorers',
            old_name='home_scorer',
            new_name='scorer',
        ),
        migrations.RemoveField(
            model_name='goalscorers',
            name='away_assist',
        ),
        migrations.RemoveField(
            model_name='goalscorers',
            name='away_scorer',
        ),
    ]
