# Generated by Django 4.2.1 on 2023-06-04 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores_fixtures', '0009_alter_goalscorers_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalscorers',
            name='team',
        ),
    ]
