# Generated by Django 4.2.1 on 2023-06-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores_fixtures', '0012_alter_goalscorers_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away_team_score',
            field=models.IntegerField(blank=True, default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team_score',
            field=models.IntegerField(blank=True, default=0, max_length=10, null=True),
        ),
    ]
