# Generated by Django 4.2.1 on 2023-07-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores_fixtures', '0013_alter_match_away_team_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalscorers',
            name='away_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='goalscorers',
            name='home_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
