# Generated by Django 4.2.1 on 2023-07-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores_fixtures', '0016_rename_matchstat_card_matchstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
