# Generated by Django 4.2.1 on 2023-07-12 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scores_fixtures', '0017_alter_match_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('not_started', 'not_started'), ('ON', 'ON'), ('HT', 'HT'), ('FT', 'FT'), ('ET', 'ET'), ('postponed', 'postponed')], default='not_started', max_length=15),
        ),
        migrations.CreateModel(
            name='MatchAdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(default=0)),
                ('additional_info', models.CharField(blank=True, max_length=1000, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores_fixtures.match')),
            ],
        ),
    ]
